config/routes.rb
Rails.application.routes.draw do

  root "pages#home"

  resources :songs, only: [:index]
  resources :artists do
    resources :songs, except: [:index]
  end
  resources :photos

  namespace :api do
    resources :artists do
      resources :songs do
        collection do
          delete "remove_multiple"
        end
      end
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs, dependent: :destroy
  has_many :photos, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  def self.order_name_asc
    order(:name)
  end

  def self.order_name_desc
    order(name: :desc)
  end

  def self.order_date_asc
    order(:created_at)
  end

  def self.order_date_desc
    order(created_at: :desc)
  end
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :artist

  mount_uploader :image, ImageUploader
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  validates :name, presence: true
end

app/controllers/api/artists_controller.rb
class Api::ArtistsController < ApplicationController

  def index
    artists = Artist.all
    render status: 200, json: artists
  end

  def show
    artist = Artist.find(params[:id])
    render status: 200, json: artist
  end

  private
  def artist_params
    params
      .require(:artist)
      .permit(
        :name, :genre
      )
  end
end

app/controllers/api/songs_controller.rb
class Api::SongsController < ApplicationController
skip_before_action :verify_authenticity_token

  def index
    artist = Artist.find(params[:artist_id])
    songs = artist.songs
    render status: 200, json: songs
  end

  def show
    artist = Artist.find(params[:artist_id])
    song = artist.songs.find(params[:id])
    render status: 200, json: song
  end

  def create
    artist = Artist.find(params[:artist_id])
    song = artist.songs.build(song_params)
    if song.save
      render status: 201, json: song
    else
      render status: 422, json: {
        errors: song.errors
      }.to_json
    end
  end

  def destroy
    @artist = Artist.find(params[:artist_id])
    song = Song.find(params[:id])
    song.destroy

    respond_to do |format|
      format.html { redirect_to artist_path(@artist), notice: 'Song successfully deleted' }
      format.json { render status: 204, location: @artist }
    end
  end

  def update
    song = Song.find(params[:id])
    if song.update(song_params)
      render status: 200, json: {
        message: "Song successfully updated",
        song: song
      }.to_json
    else
       render status: 422, json: {
        message: "The song could not be updated",
        errors: song.errors
      }.to_json
    end
  end

  def remove_multiple
    @artist = Artist.find(params[:artist_id])
    @songs = @artist.songs
    @songs.destroy_all
    respond_to do |format|
      format.html { redirect_to artist_path(@artist), notice: 'All songs deleted' }
      format.json { render status: 200, location: @artist }
    end
  end

  private
  def song_params
    params
      .require(:song)
      .permit(
        :name, :genre, :release_date, :length, :artist_id
      )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController


  def index
    @artists = Artist.order(params[:order])
    if params[:order] == "name"
      @artists = Artist.all.order(:name)
    elsif params[:order] == "name_desc"
      @artists = Artist.all.order(name: :desc)
    elsif params[:order] == "created"
      @artists = Artist.all.order(:created_at)
    elsif params[:order] == "created_desc"
      @artists = Artist.all.order(created_at: :desc)
    else
      @artists = Artist.all
    end
  end

  def show
    @artist = Artist.find(params[:id])
    @songs = @artist.songs
    @photos = @artist.photos
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      image_params.each do |image|
        @artist.photos.create(image: image)
      end
      redirect_to @artist, notice: "Artist Created Successfully"
    else
      render :new
    end
  end

  def edit
    @artist = Artist.find(params[:id])
    @photos = @artist.photos
  end

  def update
    @artist = Artist.find(params[:id])
    if @artist.update(artist_params)
      image_params.each do |image|
        @artist.photos.create!(image: image)
      end
      redirect_to @artist, notice: "Artist successfully updated"
    else
      render :edit
    end
  end

  def destroy
    @artist = Artist.find(params[:id])
    @artist.destroy
    redirect_to artists_path
  end

  private
  def image_params
    params[:images].present? ? params.require(:images) : []
  end

  private
  def artist_params
    params
      .require(:artist)
      .permit(
        :genre, :name
      )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


  @artists = Artist.all
  def home
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
    photo = Photo.find(params[:id])
    @artist = photo.artist
    photo.destroy
    redirect_to edit_artist_path(@artist), notice: "Photo successfully removed"
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def show
    artist = Artist.find(params[:artist_id])
    @song = artist.songs.find(params[:id])
  end

  def new
    artist = Artist.find(params[:artist_id])
    @song = artist.songs.build
  end

  def create
    # artist = Artist.find(params[:artist_id])
    # @song = artist.songs.create(song_params)
    # if @song.save
    #   redirect_to @song.artist, notice: "Song Created Successfully"
    # else
    #   render :new
    # end
  end

  def edit
    artist = Artist.find(params[:artist_id])
    @song = artist.songs.find(params[:id])
  end

  def update
    artist = Artist.find(params[:artist_id])
    @song = artist.songs.find(params[:id])
    if @song.update_attributes(song_params)
      redirect_to @song.artist, notice: "Song updated"
    else
      render :edit
    end
  end

  def destroy
    artist = Artist.find(params[:artist_id])
    @song = artist.songs.find(params[:id])
    @song.destroy
    redirect_to @song.artist
  end

  private
  def song_params
    params
      .require(:song)
      .permit(
        :name, :genre, :length, :release_date, :artist_id
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist, html: { multipart: true } do |f| %>
  <div class="form-group">
    <label>Artist Name</label>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Artist Genre</label>
    <%= f.text_field :genre, class: "form-control" %>
  </div>

  <label>Photos</label>
  <div class="form-group">
    <span class="btn btn-default">
      Upload Image
      <%= file_field_tag "images[]", type: :file, multiple: false %>
    </span>
    <div id="photos">
      <%= render 'photos/list' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<div class="change-artist">

<h1> Edit Artist </h1>

<%= render "form" %>
</div>

app/views/artists/index.html.erb
<div class="artist-list">


  <div class="row">
  <h1> List of Artists </h1>
  <br/>
  <div class="col-xs-12">
    <%= link_to "Sort by Name A-Z", artists_path(order: 'name'), class: "sort-button" %>
    <%= link_to "Sort by Name Z-A", artists_path(order: 'name_desc'), class: "sort-button" %>
    <%= link_to "Sort by Newest", artists_path(order: 'created'), class: "sort-button" %>
    <%= link_to "Sort by Oldest", artists_path(order: 'created_desc'), class: "sort-button" %>
  </div>
    <% @artists.each do |artist| %>
    <div class="col-xs-12 col-sm-6 col-md-4">
      <br/>
      <p class="artist-name"><%= link_to artist.name, artist_path(artist) %></p>
      <% artist.photos.each do |photo| %>
        <p><%= link_to image_tag(photo.image.thumbnail, class: "square-images"), artist_path(artist) %> </p>
      <% end %>
    </div>
    <% end %>



</div>
</div>
<div class="links-div">
<hr />
<%= link_to "Create New Artist", new_artist_path, class: "btn btn-default" %>
</div>

app/views/artists/new.html.erb
<div class="new-artist">

<h1>New Artist</h1>

<%= render "form" %>
</div>

app/views/artists/show.html.erb
<div class="row">
  <div class="col-xs-6">
    <div id="<%=@artist.id%>" class="artist-details">

      <h1> <%= @artist.name %> </h1>

      <p class="genre">Genre: <%= @artist.genre %></p>

      <h2> List of Songs: </h2>
      <ul class="list-of-songs">
        <% @artist.songs.each do |song| %>
        <!-- <input type="hidden" class="song-id" value="<%= song.id %>" > -->
        <li data-artist-id="<%= @artist.id %>" id="<%= song.id %>" class="song-name">
          <p><%=song.name%></p>

          <a href="/artists/<%= @artist.id%>/songs/<%= song.id%>/edit" class="btn btn-primary">Edit</a>
          <a href="/api/artists/<%= @artist.id %>/songs/<%=song.id%>" data-method="delete" rel="nofollow" class="btn btn-primary delete-song">Delete</a>
        <!-- <p>Duration: <%=song.length%> minutes</p> -->
        <!-- <li>Release Date: <%=song.release_date%></li> -->
        <%#= link_to 'Edit', edit_artist_song_path(song.artist, song), class: "btn btn-primary" %>
        <%#= link_to 'Delete', [song.artist, song], data: {confirm: "Are you sure you want to delete this song?" }, :method => :delete, class: "btn btn-primary delete-song" %>
        <hr/>
        </li>
        <% end %>
      </ul>
    </div>
      <%= render "songs/song", song: @artist.songs.build %>
  </div>

  <div class="col-xs-6">
    <div class="artist-image">
      <% @artist.photos.each do |photo| %>
          <%= image_tag photo.image.thumbnail %>
      <% end %>
    </div>
  </div>
</div>

<a href="/api/artists/<%= @artist.id %>/songs/remove_multiple" data-method="delete" rel="nofollow" class="btn btn-primary delete-all-songs">Delete All Songs</a>

<%#= link_to "Add Song", new_artist_song_path(@artist), class: "btn btn-success" %>
<%= link_to "Edit Artist", edit_artist_path, class: "btn btn-success" %>
<%= link_to "Delete Artist", artist_path(@artist.id), method: :delete, data: {confirm: "NOTE: Deleting an artist will delete all associated songs. \nDo you wish to continue?" }, class: "btn btn-danger" %>
<br/>
<br />
<%= link_to "Back to List of Artists", artists_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Codaisseurify</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<div class="title">
  <h1>Welcome to Codaisseurify</h1>
</div>
<div class="row">
  <div class="col-sm-6">
    <div class="box">
      <h4>List of Artists </h4>
      <div class="image-container">
        <%= link_to image_tag("http://res.cloudinary.com/meganc94/image/upload/v1505030107/artist_cttwm1.png", class: "box-image"), artists_path %>
      </div>
    </div>
  </div>
  <div class="col-sm-6">
    <div class="box">
      <h4>List of Songs </h4>
      <div class="image-container">
        <%= link_to image_tag("http://res.cloudinary.com/meganc94/image/upload/v1505030107/song_qmfub7.jpg", class: "box-image"), songs_path, class: "box-image-link" %>
      </div>
    </div>
  </div>
</div>

app/views/photos/_list.html.erb
<% if @photos %>
  <% @photos.each do |photo| %>
    <div class="panel panel-default">
      <div class="panel-heading preview">
        <%= image_tag photo.image.thumbnail %>
      </div>
      <div class="panel-body">
        <%= link_to "Delete", photo_path( photo.id ), class: "btn btn-default", method: :delete, data: { confirm: "Are you sure you want to delete this photo?" } %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Codaisseurify", root_path, class: "navbar-brand" %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Artists", artists_path %></li>
        <li><%= link_to "Songs", songs_path %></li>
      </ul>
    </div>
  </div>
</nav>

app/views/songs/_form.html.erb
<%= form_for [@song.artist, @song] do |f| %>

  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h4 class="white"><%= pluralize(@song.errors.count, "error") %> prohibited this comment from being saved:</h4>
      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li class="white"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <label>Artist</label>
    <h2 class="white"><%= @song.artist.name %></h2>
  </div>

  <div class="form-group">
    <label>Song Name</label>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Song Genre</label>
    <%= f.text_field :genre, class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Song Duration in Minutes</label>
    <%= f.number_field :length, :step => "0.01", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Release Date</label>
    <%= f.date_field :release_date, class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/songs/_song.html.erb
<%= form_for [@artist, song] do |f| %>

  <% if song.errors.any? %>
    <div id="error_explanation">
      <h4 class="white"><%= pluralize(song.errors.count, "error") %> prohibited this comment from being saved:</h4>
      <ul>
      <% song.errors.full_messages.each do |msg| %>
        <li class="white"><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <h2 class="white">Add Song to: <%= song.artist.name %></h2>
  </div>

  <div class="form-group">
    <label>Song Name</label>
    <%= f.text_field :name, class: "form-control", id: "song-name" %>
  </div>

  <!-- <div class="form-group">
    <label>Release Date</label>
    <%= f.date_field :release_date, class: "form-control", id: "release-date" %>
  </div> -->

  <div id="<%= @artist.id %>" class="actions">
    <%= f.submit "Save", class: "btn btn-primary", id: "add-song" %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1 class="white"> Edit Song </h1>

<%= render "form" %>

app/views/songs/index.html.erb
<div class="index-songs">
  <h1>List of Songs</h1>
  <div class="row">
    <% @songs.each do |song| %>
    <div class="col-sm-6">
      
      <div class="col-sm-6">
        <p>Artist: <%= song.artist.name %> </p>
        <p>Title: <%= song.name %> </p>
        <p>Genre: <%= song.genre %> </p>
        <p>Duration: <%= song.length %> minutes </p>
        <p>Release Date: <%= song.release_date %> </p>
      </div>

      <div class="col-sm-6">
        <p><%= link_to 'Edit', edit_artist_song_path(song.artist, song), class: "btn btn-primary" %></p>
        <p><%= link_to 'Delete', [song.artist, song], data: {confirm: "Are you sure you want to delete this song?" }, :method => :delete, class: "btn btn-danger"  %></p>
      </div>
      <hr />

    </div>
    <% end %>
  </div>
</div>

app/views/songs/new.html.erb
<div class="new-song">
  <h1>Create Song</h1>
<%= render "form" %>
</div>

app/views/songs/show.html.erb
<h1> <%= @song.name %></h1>